version: '3.1'

services:
  verdaccion:
    build: verdaccio-s3/
    container_name: "verdaccio"
    environment:
      - VERDACCIO_PORT=$VERDACCIO_PORT
      - VERDACCIO_S3_BUCKET=$VERDACCIO_S3_BUCKET
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    ports:
      - $VERDACCIO_PORT:$VERDACCIO_PORT
    volumes:
      - "./conf:/verdaccio/conf"
