store:
  aws-s3-storage:
    bucket: VERDACCIO_S3_BUCKET
    region: AWS_DEFAULT_REGION

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1 # no registrations allowed!

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  # scoped packages
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  # the rest of packages
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

logs:
  - { type: stdout, format: pretty, level: http }

listen:
  - 127.0.0.1:4873
